### ISSUE TITLE
Cambio en el docker compose

### ISSUE THREAD

**Issue by njavilas2015** [IgnFed/__Test#1]
Hola veo que el docker compose tiene que tener la imagen redis:6.2-alpine para que comienze a procesar! animos!

docker compose esperado
```
version: "3.5"

services:
  redis:
    image: redis:6.2-alpine
    restart: always

    ports:
      - 6379:6379

```
